"""roadmap schema prep

Revision ID: 4399b6d253bf
Revises: a6e2c8f41b90
Create Date: 2026-08-27 21:59:16.081294
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
import backend.app.models


revision: str = '4399b6d253bf'
down_revision: str | Sequence[str] | None = 'a6e2c8f41b90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_exam_date', sa.Date(), nullable=True),
    sa.Column('plan_data', sa.JSON(), nullable=True),
    sa.Column('created_at', backend.app.models.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_exam_plans_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exam_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_plans'))
    )
    with op.batch_alter_table('exam_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_plans_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_plans_user_id'), ['user_id'], unique=False)

    op.create_table('flashcard_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', backend.app.models.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_flashcard_sets_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_flashcard_sets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flashcard_sets'))
    )
    with op.batch_alter_table('flashcard_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcard_sets_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcard_sets_user_id'), ['user_id'], unique=False)

    op.create_table('profile_knowledge_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('embedding', backend.app.models.EmbeddingVector(), nullable=False),
    sa.Column('embedding_provider', sa.String(length=50), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('created_at', backend.app.models.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', backend.app.models.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('dimensions = 768', name=op.f('ck_profile_knowledge_embeddings_dimensions_supported')),
    sa.ForeignKeyConstraint(['knowledge_id'], ['profile_knowledge.id'], name=op.f('fk_profile_knowledge_embeddings_knowledge_id_profile_knowledge'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profile_knowledge_embeddings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_knowledge_embeddings')),
    sa.UniqueConstraint('knowledge_id', name='uq_profile_knowledge_embeddings_knowledge_id')
    )
    with op.batch_alter_table('profile_knowledge_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_knowledge_embeddings_knowledge_id'), ['knowledge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_knowledge_embeddings_user_id'), ['user_id'], unique=False)

    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('front_text', sa.Text(), nullable=False),
    sa.Column('back_text', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('created_at', backend.app.models.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['flashcard_sets.id'], name=op.f('fk_flashcards_set_id_flashcard_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flashcards'))
    )
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcards_set_id'), ['set_id'], unique=False)

    op.create_table('spaced_repetition_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flashcard_id', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('next_review_at', backend.app.models.UTCDateTime(), nullable=True),
    sa.Column('last_reviewed_at', backend.app.models.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], name=op.f('fk_spaced_repetition_states_flashcard_id_flashcards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_spaced_repetition_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spaced_repetition_states')),
    sa.UniqueConstraint('user_id', 'flashcard_id', name='uq_srs_user_flashcard')
    )
    with op.batch_alter_table('spaced_repetition_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spaced_repetition_states_flashcard_id'), ['flashcard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spaced_repetition_states_user_id'), ['user_id'], unique=False)



    with op.batch_alter_table('quiz_attempt_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grading_status', sa.String(length=20), server_default='not_required', nullable=False))
        batch_op.add_column(sa.Column('grading_model', sa.String(length=150), nullable=True))

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_type', sa.String(length=50), server_default='standard', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('quiz_type')

    with op.batch_alter_table('quiz_attempt_answers', schema=None) as batch_op:
        batch_op.drop_column('grading_model')
        batch_op.drop_column('grading_status')



    with op.batch_alter_table('spaced_repetition_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spaced_repetition_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_spaced_repetition_states_flashcard_id'))

    op.drop_table('spaced_repetition_states')
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcards_set_id'))

    op.drop_table('flashcards')
    with op.batch_alter_table('profile_knowledge_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_knowledge_embeddings_user_id'))
        batch_op.drop_index(batch_op.f('ix_profile_knowledge_embeddings_knowledge_id'))

    op.drop_table('profile_knowledge_embeddings')
    with op.batch_alter_table('flashcard_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcard_sets_user_id'))
        batch_op.drop_index(batch_op.f('ix_flashcard_sets_course_id'))

    op.drop_table('flashcard_sets')
    with op.batch_alter_table('exam_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_plans_course_id'))

    op.drop_table('exam_plans')
    # ### end Alembic commands ###
