"""initial schema

Revision ID: 97d9fd86a3ba
Revises:
Create Date: 2026-08-02 18:11:07.418777
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "97d9fd86a3ba"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    roles_table = op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.bulk_insert(roles_table, [{"name": "admin"}, {"name": "user"}])
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("is_initial_admin", sa.Boolean(), nullable=True),
        sa.Column("credits", sa.Float(), nullable=True),
        sa.Column("is_banned", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column(
            "preferred_model",
            sa.String(length=100),
            server_default="gpt-4o-mini",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email = lower(email)", name=op.f("ck_users_email_lowercase")
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_users_role_id_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("is_initial_admin", name=op.f("uq_users_is_initial_admin")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("instructor", sa.String(length=200), nullable=False),
        sa.Column("price", sa.Float(), server_default="0", nullable=False),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_courses_price_nonnegative")),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_courses_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
    )
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_courses_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "profile_knowledge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.String(length=200), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_profile_knowledge_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_knowledge")),
    )
    with op.batch_alter_table("profile_knowledge", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_profile_knowledge_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "generated_outputs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("output_type", sa.String(length=30), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_generated_outputs_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_outputs")),
    )
    with op.batch_alter_table("generated_outputs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_generated_outputs_course_id"), ["course_id"], unique=False
        )

    op.create_table(
        "progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("completion", sa.Float(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_progress_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_progress_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "completion >= 0 AND completion <= 1",
            name=op.f("ck_progress_completion_fraction"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_progress")),
        sa.UniqueConstraint("user_id", "course_id", name="uq_progress_user_course"),
    )
    with op.batch_alter_table("progress", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_progress_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_progress_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "quizzes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_quizzes_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quizzes")),
    )
    with op.batch_alter_table("quizzes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quizzes_course_id"), ["course_id"], unique=False
        )

    op.create_table(
        "uploaded_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("original_file_name", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("storage_provider", sa.String(length=50), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'completed', 'failed')",
            name=op.f("ck_uploaded_documents_status_valid"),
        ),
        sa.CheckConstraint(
            "file_size >= 0", name=op.f("ck_uploaded_documents_file_size_nonnegative")
        ),
        sa.CheckConstraint(
            "length(file_hash) = 64",
            name=op.f("ck_uploaded_documents_file_hash_length"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_uploaded_documents_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_uploaded_documents_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploaded_documents")),
        sa.UniqueConstraint(
            "course_id", "file_hash", name="uq_uploaded_documents_course_id_file_hash"
        ),
        sa.UniqueConstraint(
            "id", "course_id", name="uq_uploaded_documents_id_course_id"
        ),
    )
    with op.batch_alter_table("uploaded_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_uploaded_documents_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_document_chunks_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "course_id"],
            ["uploaded_documents.id", "uploaded_documents.course_id"],
            name="fk_document_chunks_document_course_uploaded_documents",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_chunk_doc_index"),
    )
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_chunks_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_chunks_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "quiz_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_quiz_attempts_quiz_id_quizzes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_quiz_attempts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "score >= 0 AND score <= 1",
            name=op.f("ck_quiz_attempts_score_fraction"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_attempts")),
    )
    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quiz_attempts_quiz_id"), ["quiz_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quiz_attempts_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "quiz_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("question_index", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("correct_option_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_quiz_questions_quiz_id_quizzes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_questions")),
        sa.UniqueConstraint("quiz_id", "question_index", name="uq_question_quiz_index"),
    )
    with op.batch_alter_table("quiz_questions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quiz_questions_quiz_id"), ["quiz_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quiz_questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quiz_questions_quiz_id"))

    op.drop_table("quiz_questions")
    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quiz_attempts_user_id"))
        batch_op.drop_index(batch_op.f("ix_quiz_attempts_quiz_id"))

    op.drop_table("quiz_attempts")
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_chunks_document_id"))
        batch_op.drop_index(batch_op.f("ix_document_chunks_course_id"))

    op.drop_table("document_chunks")
    with op.batch_alter_table("uploaded_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploaded_documents_user_id"))

    op.drop_table("uploaded_documents")
    with op.batch_alter_table("quizzes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quizzes_course_id"))

    op.drop_table("quizzes")
    with op.batch_alter_table("progress", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_progress_user_id"))
        batch_op.drop_index(batch_op.f("ix_progress_course_id"))

    op.drop_table("progress")
    with op.batch_alter_table("generated_outputs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generated_outputs_course_id"))

    op.drop_table("generated_outputs")
    with op.batch_alter_table("profile_knowledge", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profile_knowledge_user_id"))

    op.drop_table("profile_knowledge")
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_courses_owner_id"))

    op.drop_table("courses")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("roles")
    # ### end Alembic commands ###
