"""align profile document schema with models

The tables added by ``e1a2b3c4d5e6`` were created with autogenerated constraint
names and wider columns than the models declare, and without the direct
``user_id`` foreign keys the models carry. That left ``alembic check`` failing,
which in turn stopped the Compose ``migrate`` service from completing. This
brings the database to what the models describe, matching the course-side
tables those models were modelled on.

Revision ID: e74c4d3649f1
Revises: b88c7483c27d
Create Date: 2026-08-28 21:58:19.037923

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e74c4d3649f1"
down_revision: str | Sequence[str] | None = "b88c7483c27d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("profile_document_chunks", schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_profile_document_chunks_document_id_chunk_index", type_="unique"
        )
        batch_op.create_unique_constraint(
            "uq_profile_chunk_doc_index", ["document_id", "chunk_index"]
        )
        batch_op.create_foreign_key(
            "fk_profile_document_chunks_user_id_users",
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("profile_document_pages", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_profile_document_pages_user_id_users",
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("profile_document_visuals", schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_profile_document_visuals_page_id_visual_index", type_="unique"
        )
        batch_op.create_unique_constraint(
            "uq_profile_visual_page_index", ["page_id", "visual_index"]
        )

    with op.batch_alter_table("profile_processing_jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "correlation_id",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=64),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "max_attempts",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "claim_token",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=36),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "processing_stage",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=32),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "failed_stage",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=32),
            existing_nullable=True,
        )
        batch_op.drop_constraint(
            "uq_profile_processing_jobs_document_id_job_type", type_="unique"
        )
        batch_op.create_unique_constraint(
            "uq_profile_processing_jobs_doc_type", ["document_id", "job_type"]
        )


def downgrade() -> None:
    with op.batch_alter_table("profile_processing_jobs", schema=None) as batch_op:
        batch_op.drop_constraint("uq_profile_processing_jobs_doc_type", type_="unique")
        batch_op.create_unique_constraint(
            "uq_profile_processing_jobs_document_id_job_type",
            ["document_id", "job_type"],
        )
        batch_op.alter_column(
            "failed_stage",
            existing_type=sa.String(length=32),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "processing_stage",
            existing_type=sa.String(length=32),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "claim_token",
            existing_type=sa.String(length=36),
            type_=sa.VARCHAR(length=64),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "max_attempts",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'3'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "correlation_id",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=100),
            existing_nullable=True,
        )

    with op.batch_alter_table("profile_document_visuals", schema=None) as batch_op:
        batch_op.drop_constraint("uq_profile_visual_page_index", type_="unique")
        batch_op.create_unique_constraint(
            "uq_profile_document_visuals_page_id_visual_index",
            ["page_id", "visual_index"],
        )

    with op.batch_alter_table("profile_document_pages", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_profile_document_pages_user_id_users", type_="foreignkey"
        )

    with op.batch_alter_table("profile_document_chunks", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_profile_document_chunks_user_id_users", type_="foreignkey"
        )
        batch_op.drop_constraint("uq_profile_chunk_doc_index", type_="unique")
        batch_op.create_unique_constraint(
            "uq_profile_document_chunks_document_id_chunk_index",
            ["document_id", "chunk_index"],
        )
