"""add generation jobs

Revision ID: ebccfdeadee4
Revises: 2ecde7624a99
Create Date: 2026-08-30 18:26:15.173726
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
import backend


revision: str = "ebccfdeadee4"
down_revision: str | Sequence[str] | None = "2ecde7624a99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("request_payload", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="queued", nullable=False
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", backend.app.models.UTCDateTime(), nullable=False),
        sa.Column("started_at", backend.app.models.UTCDateTime(), nullable=True),
        sa.Column("claimed_at", backend.app.models.UTCDateTime(), nullable=True),
        sa.Column("heartbeat_at", backend.app.models.UTCDateTime(), nullable=True),
        sa.Column("lease_expires_at", backend.app.models.UTCDateTime(), nullable=True),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("claim_token", sa.String(length=36), nullable=True),
        sa.Column("finished_at", backend.app.models.UTCDateTime(), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("charge_amount", sa.Float(), nullable=True),
        sa.Column("charge_transaction_id", sa.Integer(), nullable=True),
        sa.Column(
            "charge_refunded", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column("generated_output_id", sa.Integer(), nullable=True),
        sa.Column("quiz_id", sa.Integer(), nullable=True),
        sa.Column("retry_of_job_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            backend.app.models.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            backend.app.models.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'running' AND attempt_count > 0 AND lease_owner IS NOT NULL AND claim_token IS NOT NULL AND claimed_at IS NOT NULL AND heartbeat_at IS NOT NULL AND lease_expires_at IS NOT NULL AND heartbeat_at >= claimed_at AND lease_expires_at > heartbeat_at AND finished_at IS NULL) OR (status <> 'running' AND lease_owner IS NULL AND claim_token IS NULL AND claimed_at IS NULL AND heartbeat_at IS NULL AND lease_expires_at IS NULL)",
            name=op.f("ck_generation_jobs_lease_state_valid"),
        ),
        sa.CheckConstraint(
            "(status IN ('succeeded', 'failed') AND finished_at IS NOT NULL) OR (status IN ('queued', 'running') AND finished_at IS NULL)",
            name=op.f("ck_generation_jobs_finished_state_valid"),
        ),
        sa.CheckConstraint(
            "job_type <> 'generate_quiz' OR generated_output_id IS NULL",
            name=op.f("ck_generation_jobs_quiz_result_shape"),
        ),
        sa.CheckConstraint(
            "job_type <> 'generate_study_guide' OR quiz_id IS NULL",
            name=op.f("ck_generation_jobs_study_guide_result_shape"),
        ),
        sa.CheckConstraint(
            "job_type <> 'generate_flashcard' OR quiz_id IS NULL",
            name=op.f("ck_generation_jobs_flashcard_result_shape"),
        ),
        sa.CheckConstraint(
            "job_type IN ('generate_study_guide', 'generate_quiz', 'generate_flashcard')",
            name=op.f("ck_generation_jobs_job_type_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'failed' OR (last_error_code IS NOT NULL AND length(trim(last_error_code, ' \t\n\r\x0b\x0c')) > 0)",
            name=op.f("ck_generation_jobs_failed_error_code_nonblank"),
        ),
        sa.CheckConstraint(
            "status <> 'queued' OR attempt_count < max_attempts",
            name=op.f("ck_generation_jobs_queued_attempts_available"),
        ),
        sa.CheckConstraint(
            "status <> 'running' OR (claim_token IS NOT NULL AND length(claim_token) = 36)",
            name=op.f("ck_generation_jobs_running_claim_token_length"),
        ),
        sa.CheckConstraint(
            "status <> 'running' OR (lease_owner IS NOT NULL AND length(trim(lease_owner, ' \t\n\r\x0b\x0c')) > 0)",
            name=op.f("ck_generation_jobs_running_lease_owner_nonblank"),
        ),
        sa.CheckConstraint(
            "status <> 'succeeded' OR generated_output_id IS NOT NULL OR quiz_id IS NOT NULL",
            name=op.f("ck_generation_jobs_succeeded_has_result"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed')",
            name=op.f("ck_generation_jobs_status_valid"),
        ),
        sa.CheckConstraint(
            "attempt_count <= max_attempts",
            name=op.f("ck_generation_jobs_attempt_count_within_limit"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0",
            name=op.f("ck_generation_jobs_attempt_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "charge_amount IS NULL OR charge_amount > 0",
            name=op.f("ck_generation_jobs_charge_amount_positive"),
        ),
        sa.CheckConstraint(
            "charge_refunded = false OR charge_amount IS NOT NULL",
            name=op.f("ck_generation_jobs_refund_needs_charge"),
        ),
        sa.CheckConstraint(
            "charge_transaction_id IS NULL OR charge_amount IS NOT NULL",
            name=op.f("ck_generation_jobs_charge_transaction_needs_amount"),
        ),
        sa.CheckConstraint(
            "max_attempts > 0", name=op.f("ck_generation_jobs_max_attempts_positive")
        ),
        sa.ForeignKeyConstraint(
            ["charge_transaction_id"],
            ["credit_transactions.id"],
            name=op.f("fk_generation_jobs_charge_transaction_id_credit_transactions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_generation_jobs_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["generated_output_id"],
            ["generated_outputs.id"],
            name=op.f("fk_generation_jobs_generated_output_id_generated_outputs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_generation_jobs_quiz_id_quizzes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["retry_of_job_id"],
            ["generation_jobs.id"],
            name=op.f("fk_generation_jobs_retry_of_job_id_generation_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_generation_jobs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_jobs")),
        sa.UniqueConstraint(
            "retry_of_job_id", name="uq_generation_jobs_retry_of_job_id"
        ),
    )
    with op.batch_alter_table("generation_jobs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_generation_jobs_claimable",
            ["status", "available_at", "id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_generation_jobs_course_created",
            ["course_id", "created_at", "id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_generation_jobs_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            "ix_generation_jobs_recoverable",
            ["status", "lease_expires_at", "id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_generation_jobs_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "ix_generation_jobs_user_status", ["user_id", "status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("generation_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_generation_jobs_user_status")
        batch_op.drop_index(batch_op.f("ix_generation_jobs_user_id"))
        batch_op.drop_index("ix_generation_jobs_recoverable")
        batch_op.drop_index(batch_op.f("ix_generation_jobs_course_id"))
        batch_op.drop_index("ix_generation_jobs_course_created")
        batch_op.drop_index("ix_generation_jobs_claimable")

    op.drop_table("generation_jobs")
    # ### end Alembic commands ###
