"""create canonical schema

Revision ID: 20260804_0001
Revises:
Create Date: 2026-08-04 00:10:36.241314
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "20260804_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    roles = sa.table("roles", sa.column("name", sa.String(length=32)))
    op.bulk_insert(roles, [{"name": "admin"}, {"name": "user"}])
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column(
            "credits",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("(100.00)"),
            nullable=False,
        ),
        sa.Column(
            "preferred_model",
            sa.String(length=100),
            server_default=sa.text("'gpt-4o-mini'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("credits >= 0", name=op.f("ck_users_credits_nonnegative")),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_users_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_role_id"), ["role_id"], unique=False)

    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("instructor", sa.String(length=200), nullable=False),
        sa.Column(
            "price",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("(0.00)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_courses_price_nonnegative")),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_courses_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
    )
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.create_index(
            "ix_courses_owner_active_created",
            ["owner_id", "deleted_at", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_courses_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "profile_knowledge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.String(length=200), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_profile_knowledge_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_knowledge")),
    )
    with op.batch_alter_table("profile_knowledge", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_profile_knowledge_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "ix_profile_knowledge_user_topic", ["user_id", "topic"], unique=False
        )

    op.create_table(
        "generated_outputs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("output_type", sa.String(length=30), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_generated_outputs_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_outputs")),
    )
    with op.batch_alter_table("generated_outputs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_generated_outputs_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            "ix_generated_outputs_course_type_created",
            ["course_id", "output_type", "created_at"],
            unique=False,
        )

    op.create_table(
        "progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column(
            "completion",
            sa.Numeric(precision=5, scale=4),
            server_default=sa.text("(0.0000)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completion >= 0 AND completion <= 1",
            name=op.f("ck_progress_completion_fraction"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_progress_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_progress_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_progress")),
        sa.UniqueConstraint("user_id", "course_id", name="uq_progress_user_course"),
    )
    with op.batch_alter_table("progress", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_progress_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_progress_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "quizzes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_quizzes_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quizzes")),
    )
    with op.batch_alter_table("quizzes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_quizzes_course_created", ["course_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quizzes_course_id"), ["course_id"], unique=False
        )

    op.create_table(
        "uploaded_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=127), nullable=False),
        sa.Column("extension", sa.String(length=16), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'queued'"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'processing', 'ready', 'failed', 'cancelled')",
            name=op.f("ck_uploaded_documents_status_valid"),
        ),
        sa.CheckConstraint(
            "byte_size >= 0", name=op.f("ck_uploaded_documents_byte_size_nonnegative")
        ),
        sa.CheckConstraint(
            "length(sha256) = 64", name=op.f("ck_uploaded_documents_sha256_length")
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_uploaded_documents_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploaded_documents")),
        sa.UniqueConstraint(
            "course_id", "idempotency_key", name="uq_document_course_idempotency"
        ),
        sa.UniqueConstraint("id", "course_id", name="uq_document_id_course"),
        sa.UniqueConstraint("public_id", name=op.f("uq_uploaded_documents_public_id")),
        sa.UniqueConstraint(
            "storage_key", name=op.f("uq_uploaded_documents_storage_key")
        ),
    )
    with op.batch_alter_table("uploaded_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_uploaded_documents_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            "ix_uploaded_documents_course_status_created",
            ["course_id", "status", "created_at"],
            unique=False,
        )
        batch_op.create_index("ix_uploaded_documents_sha256", ["sha256"], unique=False)

    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "chunk_index >= 0", name=op.f("ck_document_chunks_chunk_index_nonnegative")
        ),
        sa.CheckConstraint(
            "page_number IS NULL OR page_number >= 1",
            name=op.f("ck_document_chunks_page_number_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "course_id"],
            ["uploaded_documents.id", "uploaded_documents.course_id"],
            name="fk_chunk_document_course",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_chunk_doc_index"),
    )
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_document_chunks_course_document_index",
            ["course_id", "document_id", "chunk_index"],
            unique=False,
        )

    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'queued'"),
            nullable=False,
        ),
        sa.Column(
            "attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("claim_token", sa.String(length=36), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'running' AND lease_owner IS NOT NULL AND claim_token IS NOT NULL AND claimed_at IS NOT NULL AND heartbeat_at IS NOT NULL AND lease_expires_at IS NOT NULL AND finished_at IS NULL) OR (status <> 'running' AND lease_owner IS NULL AND claim_token IS NULL AND claimed_at IS NULL AND heartbeat_at IS NULL AND lease_expires_at IS NULL)",
            name=op.f("ck_processing_jobs_lease_state_valid"),
        ),
        sa.CheckConstraint(
            "(status IN ('succeeded', 'failed', 'cancelled') AND finished_at IS NOT NULL) OR (status IN ('queued', 'running') AND finished_at IS NULL)",
            name=op.f("ck_processing_jobs_finished_state_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_processing_jobs_status_valid"),
        ),
        sa.CheckConstraint(
            "attempt_count <= max_attempts",
            name=op.f("ck_processing_jobs_attempt_count_within_limit"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0",
            name=op.f("ck_processing_jobs_attempt_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "max_attempts > 0", name=op.f("ck_processing_jobs_max_attempts_positive")
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "course_id"],
            ["uploaded_documents.id", "uploaded_documents.course_id"],
            name="fk_job_document_course",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
        sa.UniqueConstraint("document_id", "job_type", name="uq_job_document_type"),
    )
    with op.batch_alter_table("processing_jobs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_processing_jobs_claimable",
            ["status", "available_at", "id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_processing_jobs_course_created",
            ["course_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_processing_jobs_recoverable",
            ["status", "lease_expires_at", "id"],
            unique=False,
        )

    op.create_table(
        "quiz_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "score >= 0 AND score <= 1", name=op.f("ck_quiz_attempts_score_fraction")
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_quiz_attempts_quiz_id_quizzes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_quiz_attempts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_attempts")),
    )
    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_quiz_attempts_quiz_created", ["quiz_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quiz_attempts_quiz_id"), ["quiz_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quiz_attempts_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "quiz_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("question_index", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("correct_option_index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "correct_option_index >= 0",
            name=op.f("ck_quiz_questions_correct_option_index_nonnegative"),
        ),
        sa.CheckConstraint(
            "question_index >= 0",
            name=op.f("ck_quiz_questions_question_index_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_quiz_questions_quiz_id_quizzes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_questions")),
        sa.UniqueConstraint("quiz_id", "question_index", name="uq_question_quiz_index"),
    )
    with op.batch_alter_table("quiz_questions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quiz_questions_quiz_id"), ["quiz_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quiz_questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quiz_questions_quiz_id"))

    op.drop_table("quiz_questions")
    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quiz_attempts_user_id"))
        batch_op.drop_index(batch_op.f("ix_quiz_attempts_quiz_id"))
        batch_op.drop_index("ix_quiz_attempts_quiz_created")

    op.drop_table("quiz_attempts")
    with op.batch_alter_table("processing_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_processing_jobs_recoverable")
        batch_op.drop_index("ix_processing_jobs_course_created")
        batch_op.drop_index("ix_processing_jobs_claimable")

    op.drop_table("processing_jobs")
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_index("ix_document_chunks_course_document_index")

    op.drop_table("document_chunks")
    with op.batch_alter_table("uploaded_documents", schema=None) as batch_op:
        batch_op.drop_index("ix_uploaded_documents_sha256")
        batch_op.drop_index("ix_uploaded_documents_course_status_created")
        batch_op.drop_index(batch_op.f("ix_uploaded_documents_course_id"))

    op.drop_table("uploaded_documents")
    with op.batch_alter_table("quizzes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quizzes_course_id"))
        batch_op.drop_index("ix_quizzes_course_created")

    op.drop_table("quizzes")
    with op.batch_alter_table("progress", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_progress_user_id"))
        batch_op.drop_index(batch_op.f("ix_progress_course_id"))

    op.drop_table("progress")
    with op.batch_alter_table("generated_outputs", schema=None) as batch_op:
        batch_op.drop_index("ix_generated_outputs_course_type_created")
        batch_op.drop_index(batch_op.f("ix_generated_outputs_course_id"))

    op.drop_table("generated_outputs")
    with op.batch_alter_table("profile_knowledge", schema=None) as batch_op:
        batch_op.drop_index("ix_profile_knowledge_user_topic")
        batch_op.drop_index(batch_op.f("ix_profile_knowledge_user_id"))

    op.drop_table("profile_knowledge")
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_courses_owner_id"))
        batch_op.drop_index("ix_courses_owner_active_created")

    op.drop_table("courses")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_role_id"))

    op.drop_table("users")
    op.drop_table("roles")
    # ### end Alembic commands ###
