from datetime import date


POLICY_EFFECTIVE_DATE = date(2026, 9, 12)
TERMS_POLICY_KEY = "terms_of_service"
TERMS_POLICY_VERSION = "1.0"
PRIVACY_POLICY_KEY = "privacy_notice"
PRIVACY_POLICY_VERSION = "1.0"

REGISTRATION_POLICY_VERSIONS = (
    (TERMS_POLICY_KEY, TERMS_POLICY_VERSION),
    (PRIVACY_POLICY_KEY, PRIVACY_POLICY_VERSION),
)
